[tool.autopep8]
max_line_length = 120
ignore = ["E501", "W503", "E704", "E127", "E128", "E124", "E125", "E126", "E129"]
aggressive = 0
experimental = false
hang_closing = false
# CRITICAL: Prevent string literal breaking - AGGRESSIVE = 0 to prevent breaking

[tool.black]
line-length = 120
target-version = ['py311']
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = ["E501", "W503", "E203"]
