name: Building All Containers

on:
  push:
    branches: [ 'main' ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  workflow_setup:
    name: Setup variables 
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      repo_owner: ${{ steps.repo_owner.outputs.lowercase }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Lowercase repo owner
        id: repo_owner
        run: echo "lowercase=$(echo ${{ github.repository_owner }} | tr \"[:upper:]\" \"[:lower:]\")" >>$GITHUB_OUTPUT
        shell: bash

  build_container:
    name: Build invoke_ai container
    needs: workflow_setup
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-invoke_ai-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-invoke_ai
            ${{ runner.os }}-buildx
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Metadata
        id: meta_invoke_ai
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ needs.workflow_setup.outputs.repo_owner }}/invoke_ai
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
          labels: |
            org.opencontainers.image.title=Invoke AI
            org.opencontainers.image.description=Invoke AI Webservice
            org.opencontainers.image.vendor=https://github.com/Echsecutor
  
      - name: Build node image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          context: ./
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_invoke_ai.outputs.tags }}
          labels: ${{ steps.meta_invoke_ai.outputs.labels }}
          outputs: type=docker,dest=/tmp/invoke_ai.tar
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new


      - name: Upload docker image artifacts
        uses: actions/upload-artifact@v3
        with:
          name: invoke_ai
          path: /tmp/invoke_ai.tar
          retention-days: 1
      # Temp fix
      # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#github-cache
      # https://github.com/docker/build-push-action/issues/252
      # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
